name: Python Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-html  # Додано плагін pytest-html для створення HTML звіту
        pip install pygame
        # If you have a requirements.txt file, uncomment the following line:
        # pip install -r requirements.txt
    - name: Run tests and generate HTML report
      run: |
        pytest tests/ --html=report.html